SRCS =	srcs/ft_strlen.c srcs/ft_split.c srcs/ft_isprint.c srcs/ft_strtrim.c srcs/ft_strrchr.c \
		srcs/ft_strdup.c srcs/ft_putstr_fd.c  srcs/ft_memset.c srcs/ft_isascii.c srcs/ft_isdigit.c \
		srcs/ft_isalnum.c srcs/ft_bzero.c  srcs/ft_strlcat.c srcs/ft_memcmp.c  srcs/ft_putnbr_fd.c \
		srcs/ft_putendl_fd.c srcs/ft_memcpy.c srcs/ft_substr.c srcs/ft_strncmp.c srcs/ft_putchar_fd.c \
		srcs/ft_calloc.c srcs/ft_atoi.c srcs/ft_itoa.c srcs/ft_strlcpy.c srcs/ft_memmove.c \
		srcs/ft_isalpha.c srcs/ft_strchr.c srcs/ft_memchr.c srcs/ft_strnstr.c srcs/ft_striteri.c  \
		srcs/ft_strmapi.c srcs/ft_strjoin.c srcs/ft_toupper.c srcs/ft_tolower.c srcs/ft_is_numric.c \
		srcs/ft_strcmp.c srcs/ft_is_uniquenum.c srcs/ft_is_in_bound.c srcs/ft_atol.c srcs/ft_lstclear_bonus.c\
		srcs/ft_lstlast_bonus.c srcs/ft_lstdelone_bonus.c srcs/ft_lstmap_bonus.c srcs/ft_lstsize_bonus.c \
		srcs/ft_lstiter_bonus.c srcs/ft_lstnew_bonus.c srcs/ft_lstadd_back_bonus.c srcs/ft_lstadd_front_bonus.c

OBJS = $(SRCS:srcs/%.c=obj/%.o)

NAME = libft.a

CC = cc

CFLAGS = -Wall -Wextra -Werror

all : $(NAME)

$(NAME) : $(OBJS)
	ar crs $@ $^
	echo "library built"

obj/%.o : srcs/%.c
	mkdir -p obj
	$(CC) $(CFLAGS) -I./include -c $< -o $@
	
clean :
	rm -f $(OBJS) $(BONOBJ)
	rm -rf obj
	echo "libft Cleaned"
fclean : clean
	rm -f $(NAME)
	echo "libft Fcleaned"
re : fclean all
	echo "libft re"
.PHONY: all clean fclean re bonus 

